<div class="search ">
    <form class="form-inline" method="post" action="index.php">
        <div class="input-group input-group-lg col-md-12">
            <span class="input-group-addon " id="search">URL</span>
            <input type="text" name="search" class="form-control " aria-describedby="search">
        </div>
        <br><br>
        <div class="text-center">
            <button type="submit" class="btn btn-lg btn-success get_loader start">Start</button>
        </div>
    </form>
</div>