<div class="row">
    <div class="col-sm-5 col-md-offset-1 well">
        <h5>Count new products today: <b><?= $count[0]?></b> </h5>
    </div>

    <div class="col-sm-5 col-md-offset-1 well">
        <h5>Count send massege today: <b><?= $count[1]?></b> </h5>
    </div>
</div>

<div>
    <form class="form-inline" method="post" action="index.php">
        <input type="hidden" name="send_message" value='send'>
        <div class="text-center">
            <button type="submit" class="btn btn-success btn-lg send_message">Send Messages</button>
        </div>
    </form>
</div>
<br><br>
