<div class="row">
    <div class="col-sm-5 col-md-offset-1 well">
        <h5>Count new products today: <b><span class="no_send_masseges"><?= $noSend?><span></b> </h5>
    </div>

    <div class="send_button">
        <div class="col-sm-5 col-md-offset-1 well">
            <h5>Count send massege today: <b><span class="send_messages"><?= $send?><span></b> </h5>
        </div>
    </div>
</div>

<div>
    <form class="form-inline" method="post" action="index.php">
        <input type="hidden" name="send_message" value='send'>
        <div class="text-center">
            <button type="submit" class="btn btn-success btn-lg get_loader send_message_button">Send 20 Messages </button>
        </div>
    </form>
</div>
<br><br>
