<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bot</title>
    <script src="js\jquery.js"></script>
    <script src="js\common.js"></script>
    <link rel="stylesheet" href="bootstrap\css\bootstrap.css">
    <script src="bootstrap\js\bootstrap.js"></script>
    <link rel="stylesheet" href="css\style.css">
</head>
<body>
<div class="nav_panel">
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="index.php">Scrub  leboncoin.fr</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="http://parser:8080/?count=get">Home</a></li>
                <li class="active"><a href="http://parser:8080/?message=get">Send Messages</a></li>
            </ul>
        </div>
    </nav>
</div>
<div class="container">
    <?php include($view); ?>
</div>
</body>
</html>